sudo: required
language: node_js
node_js: "8"

script: skip

jobs:
  include:
    - stage: Tests
      script: echo "No tests at the moment"

    - stage: Build and push image
      services:
        - docker
      install: skip
      before_script:
        - docker build -t gela/netstats .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag gela/netstats gela/netstats:latest
        - docker push gela/netstats:latest
        - docker tag gela/netstats gela/netstats:$TRAVIS_BUILD_ID
        - docker push gela/netstats:$TRAVIS_BUILD_ID

    - stage: Build and push image (tagged)
      services:
        - docker
      install: skip
      before_script:
        - docker build -t gela/netstats .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag gela/netstats gela/netstats:latest
        - docker push gela/netstats:latest
        - docker tag gela/netstats gela/netstats:testnet
        - docker push gela/netstats:testnet
        - docker tag gela/netstats gela/netstats:$TRAVIS_TAG
        - docker push gela/netstats:$TRAVIS_TAG

stages:
  - name: Lint
  - name: Tests
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = gela/netstats
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = gela/netstats
